# This file is autogenerated from tools/update-framework.R
# DO NOT MODIFY BY HAND as all changes will be overwritten

#' @title Enterprise Attack Taxonomy v2.0
#' @name enterprise_attack
#' @note Id: `bundle--83dad14b-ae53-4473-9f95-5ae37c8eaa5d`
#' @note Last updated: 2020-06-17
#' @references <https://github.com/mitre/cti/raw/master/enterprise-attack/enterprise-attack.json>
#' @docType data
NULL

#' @title Mobile Attack Taxonomy v2.0
#' @name mobile_attack
#' @note Id: `bundle--d22f39d8-4fa0-4557-a925-1d7bbaffaa46`
#' @note Last updated: 2020-06-17
#' @references <https://github.com/mitre/cti/raw/master/mobile-attack/mobile-attack.json>
#' @docType data
NULL

#' @title Pre-Attack Taxonomy v2.0
#' @name pre_attack
#' @note Id: `bundle--803f51fd-e986-493c-9ab1-0b33b42a4dec`
#' @note Last updated: 2020-06-17
#' @references <https://github.com/mitre/cti/raw/master/pre-attack/pre-attack.json>
#' @docType data
NULL

#' @title Combined ATT&CK Matricies Tactics, Techniques and Technique detail
#' @name tidy_attack
#' @note Last updated: 2020-06-17
#' @docType data
NULL

#' @title Tactics factors (generally for sorting & pretty-printing)
#' @name tactics_f
#' @note Last updated: 2020-06-17
#' @docType data
NULL